name: Windows-Strawberry

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows-latest']
        perl: [ '5.38', '5.36' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}
        distribution: strawberry
    - name: perl -V
      run: perl -V
    - name: Install Dependencies
      run: cpanm --installdeps .
    - name: Update Git Submodule for Brotli
      run : git submodule update --init
    - name: Build Module
      run: |
        perl Makefile.PL
        gmake
    - name: Test Module
      run: gmake test
