name: Ubuntu Matrix Testing

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        perl: ["5.40", "5.38", "5.36", "5.34"]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}
    - name: perl -V
      run: perl -V
    - name: Install Dependencies
      run: cpanm --installdeps .
    - name: Update Git Submodule for Brotli
      run : git submodule update --init
    - name: Build Module
      run: |
        perl Makefile.PL
        make
    - name: Test Module
      run: make test
